# neural-network related toy examples

In [4]:
import torch
from torch.nn.utils.rnn import pad_sequence
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

# pad

In [5]:
import torch.nn.functional as F

input_tensor = torch.Tensor(3, 1)
print(input_tensor)
padded_tensor = F.pad(input_tensor, (0, 2), mode='replicate')
padded_tensor

tensor([[1.4013e-45],
        [4.5748e-41],
        [6.0536e-43]])


tensor([[1.4013e-45, 1.4013e-45, 1.4013e-45],
        [4.5748e-41, 4.5748e-41, 4.5748e-41],
        [6.0536e-43, 6.0536e-43, 6.0536e-43]])

In [6]:
pad = nn.ConstantPad2d((0, 2), 0)
pad(input_tensor)

tensor([[1.4013e-45, 0.0000e+00, 0.0000e+00],
        [4.5748e-41, 0.0000e+00, 0.0000e+00],
        [6.0536e-43, 0.0000e+00, 0.0000e+00]])

# Dropout
Dropout을 적용하고 싶은 레이어 전에 Dropout을 넣어줘야 함<br>
train시에는 꺼지지 않은 값이 2배가 됨

In [7]:
x = torch.Tensor([[1,2,3,4], [4,5,6,7]])
nn.Dropout(0.5).forward(x)

tensor([[ 2.,  4.,  6.,  8.],
        [ 8., 10.,  0.,  0.]])

# nn.CrossEntropyLoss()
logsoftmax + nllloss이기 때문에 모델 안에 softmax레이어를 넣을 필요 없음<br>
target은 long이어야 하고 input은 데이터 개수 x output_dim(=카테고리개수)여야 함<br>
output은 데이터개수 차원이고 안의 내용은 카테고리 숫자여야함 <br>

In [8]:
>>> loss = nn.CrossEntropyLoss()
>>> input = torch.randn(3, 5, requires_grad=True)
>>> target = torch.empty(3, dtype=torch.long).random_(5)
>>> output = loss(input, target)
>>> output.backward()

In [9]:
target.shape, input.shape

(torch.Size([3]), torch.Size([3, 5]))

In [10]:
input

tensor([[-1.2819, -0.9385, -0.6472, -1.4165,  0.3229],
        [ 1.2446, -1.0230, -0.7168,  0.5386,  0.1357],
        [-0.3830, -0.6570,  0.7784, -0.3992,  1.2075]], requires_grad=True)

In [11]:
target

tensor([2, 1, 1])

## layer norm

In [12]:
input = torch.randn(3, 4)
# With Learnable Parameters
m = nn.LayerNorm(input.size()[1:])

In [13]:
input.shape, m(input).shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [14]:
m(input).mean(dim = 1)

tensor([ 2.9802e-08, -1.4901e-08,  5.9605e-08], grad_fn=<MeanBackward1>)

In [15]:
m(input).std(dim = 1)

tensor([1.1547, 1.1547, 1.1547], grad_fn=<StdBackward0>)