# neural-network related toy examples

In [51]:
import torch
from torch.nn.utils.rnn import pad_sequence
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F

# pad

In [53]:
import torch.nn.functional as F

input_tensor = torch.Tensor(3, 1)
print(input_tensor)
padded_tensor = F.pad(input_tensor, (0, 2), mode='replicate')
padded_tensor

tensor([[-1.3055e-27],
        [ 4.5845e-41],
        [-2.4656e+23]])


tensor([[-1.3055e-27, -1.3055e-27, -1.3055e-27],
        [ 4.5845e-41,  4.5845e-41,  4.5845e-41],
        [-2.4656e+23, -2.4656e+23, -2.4656e+23]])

In [54]:
pad = nn.ConstantPad2d((0, 2), 0)
pad(input_tensor)

tensor([[-1.3055e-27,  0.0000e+00,  0.0000e+00],
        [ 4.5845e-41,  0.0000e+00,  0.0000e+00],
        [-2.4656e+23,  0.0000e+00,  0.0000e+00]])

# Dropout
Dropout을 적용하고 싶은 레이어 전에 Dropout을 넣어줘야 함<br>
train시에는 꺼지지 않은 값이 2배가 됨

In [ ]:
x = torch.Tensor([[1,2,3,4], [4,5,6,7]])
nn.Dropout(0.5).forward(x)

tensor([[0., 0., 0., 0.],
        [8., 0., 0., 0.]])

# nn.CrossEntropyLoss()
logsoftmax + nllloss이기 때문에 모델 안에 softmax레이어를 넣을 필요 없음<br>
target은 long이어야 하고 input은 데이터 개수 x output_dim(=카테고리개수)여야 함<br>
output은 데이터개수 차원이고 안의 내용은 카테고리 숫자여야함 <br>

In [ ]:
>>> loss = nn.CrossEntropyLoss()
>>> input = torch.randn(3, 5, requires_grad=True)
>>> target = torch.empty(3, dtype=torch.long).random_(5)
>>> output = loss(input, target)
>>> output.backward()

In [ ]:
target.shape, input.shape

(torch.Size([3]), torch.Size([3, 5]))

In [ ]:
input

tensor([[-0.5201,  0.9689,  0.0953, -1.2881,  0.0179],
        [-0.5532, -1.0832, -1.5432, -2.9757, -0.6711],
        [ 1.0784,  0.6373,  0.2693,  0.7127,  0.7822]], requires_grad=True)

In [ ]:
target

tensor([2, 0, 1])

## layer norm

In [1]:
input = torch.randn(3, 4)
# With Learnable Parameters
m = nn.LayerNorm(input.size()[1:])

NameError: name 'torch' is not defined

In [2]:
input.shape, m(input).shape

AttributeError: 'function' object has no attribute 'shape'

In [3]:
m(input).mean(dim = 1)

NameError: name 'm' is not defined

In [ ]:
m(input).std(dim = 1)