## 1. 딥러닝 프레임워크 
딥러닝 프레임워크는 왜 필요할까요?

딥러닝을 하기 위해선 이런 것들이 필요합니다. 
- 역전파 기능
- 모델을 gpu에서 돌릴 수 있도록 하는 기능 
- 데이터를 gpu에 올리는 기능
- 모델 구조를 구현
- 역전파할 때의 optimizer
- learning rate 조정을 할 수 있는 scheduler
- 기타 등등...

이것들을 매번 구현하기에는 시간도 오래걸리고 매번 효율화를 할 수 없습니다.<br>
그래서 우리는 딥러닝 프레임워크를 사용하여 **비교적 간단하게(!)**구혈 할 수 있습니다<br>
대표적인 프레임워크로는 tensorflow와 pyTorch가 있습니다

## 2. tensorflow vs. torch

In [12]:
import tensorflow as tf
import torch
import numpy as np

## 3. torch 기본 텐서조작 

torch의 자료형으로는 tensor가 있습니다. tensor는 기본적으로 numpy.array와 유사하며 메소드도 공유하고 있습니다.<br>
numpy.array를 잠깐 복습해봅시다.

In [31]:
X = np.array([[0, 1, 0], [0, 0, 0]])
print(X) 
print(X.shape)

[[0 1 0]
 [0 0 0]]
(2, 3)


In [32]:
X = np.zeros((2, 5))
print(X)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### 문제 1: 2 by 3 np.array를 1 by 6으로 만들어보세요
**hint : reshape**

In [79]:
# X.reshape((-1, 6))

이 때 shape이 (1, 6)과 (6,)은 다름을 알아둡시다! 

In [34]:
np.ones(6), np.ones((1, 6))

(array([1., 1., 1., 1., 1., 1.]), array([[1., 1., 1., 1., 1., 1.]]))

torch의 tensor는 이와 매우 유사합니다. 이 때, torch.Tensor와 torch.tensor는 사용법이 다름을 유의합시다

In [36]:
X = torch.Tensor(3, 5) # 3 by 5 random tensor생성, np.random.rand와 같은 기능

In [37]:
X

tensor([[1.1328e+33, 1.8394e+25, 6.6397e-24, 3.0929e-41, 1.5695e-43],
        [0.0000e+00, 1.1210e-43, 0.0000e+00, 2.5944e-24, 3.0929e-41],
        [5.1848e-44, 0.0000e+00,        nan, 3.0929e-41, 1.8888e+31]])

In [41]:
X = torch.tensor([3, 6]) # torch.tensor는 리스트나 어레이를 받아 텐서로 만들어줍니다

In [42]:
X

tensor([3, 6])

numpy.array를 torch의 tensor로, 또 torch의 tensor를 numpy.array로 옮길 수 있습니다

In [57]:
np_x = np.ones((3, 5))
print(np_x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [58]:
torch_x = torch.from_numpy(np_x)
print(torch_x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)


tensor에도 다양한 메소드가 있습니다. 그 중 가장 많이 쓰이는 것 위주로 배워봅시다.<br> 외의 메소드에 대해서는 공식 문서를 참고합시다.
https://pytorch.org/docs/stable/tensors.html

### squeeze / unsqueeze
squeeze와 unsqueeze는 차원을 줄이거나 늘릴 때 사용하는 메소드입니다

In [61]:
print(torch_x.shape)
torch_x = torch_x.unsqueeze(0)
print(torch_x.shape)         # unsqueeze는 입력으로 받은 차원을 하나 더 생성해줍니다
torch_x = torch_x.squeeze(0) # squeeze는 입력으로 받은 차원의 크기 1이라면 차원을 제거해줍니다
print(torch_x.shape) 
torch_x = torch_x.squeeze(1) # 차원의 크기가 1이 아니라면 제거할 수 없습니다
print(torch_x.shape) 

torch.Size([3, 5])
torch.Size([1, 3, 5])
torch.Size([3, 5])
torch.Size([3, 5])


### transpose / permute
transpose와 permute는 차원의 위치를 변경하는데 사용됩니다

In [67]:
torch_x = torch_x.permute(1, 0) # 1번째 차원을 0번째 차원으로, 0번째 차원을 1번째 차원으로
print(torch_x.shape
      
torch_x = torch_x.transpose(1, 0) # 1번째 차원을 0번째 차원으로, 0번빼 차원을 1번째 차원으로
print(torch_x.shape)

torch.Size([5, 3])
torch.Size([3, 5])


### view
np.array의 reshape과 비슷합니다. 그러나 작동방식이 쭉 한줄로 펼친 후 shape에 맞게 자르는 것임에 주의합니다. <br>
그래서 view의 사용은 최대한 자제하는 것이 좋습니다.

In [72]:
x = torch.arange(1, 13)
print(x)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


In [76]:
x_2_6 = x.view(2, 6)
x_2_6

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [77]:
x_2_6.view(6, 2)

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

### 문제 2 : x_2_6을  위와 같이 만드려면 어떻게 해야할까요?
tensor([[ 1,  7],<br>
        [ 2,  8],<br>
        [ 3,  9],<br>
        [ 4, 10],<br>
        [ 5, 11],<br>
        [ 6, 12]])<br>
**hint : 방금 배움**

In [80]:
# x_2_6.transpose(1, 0)

## 4. Neural Network 

### input output